// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: usecases/eg/lpc/messages.proto

package lpc

import (
	common_types "github.com/enbility/eebus-grpc/rpc_services/common_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
}

func (x *ConsumptionLimitRequest) Reset() {
	*x = ConsumptionLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitRequest) ProtoMessage() {}

func (x *ConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumptionLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *ConsumptionLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type ConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *common_types.LoadLimit `protobuf:"bytes,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ConsumptionLimitResponse) Reset() {
	*x = ConsumptionLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitResponse) ProtoMessage() {}

func (x *ConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumptionLimitResponse) GetLimit() *common_types.LoadLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type WriteConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	Limit               *common_types.LoadLimit     `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *WriteConsumptionLimitRequest) Reset() {
	*x = WriteConsumptionLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConsumptionLimitRequest) ProtoMessage() {}

func (x *WriteConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*WriteConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{2}
}

func (x *WriteConsumptionLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteConsumptionLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteConsumptionLimitRequest) GetLimit() *common_types.LoadLimit {
	if x != nil {
		return x.Limit
	}
	return nil
}

type WriteConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorNumber *uint64 `protobuf:"varint,1,opt,name=error_number,json=errorNumber,proto3,oneof" json:"error_number,omitempty"`
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	MsgCounter  uint64  `protobuf:"varint,3,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
}

func (x *WriteConsumptionLimitResponse) Reset() {
	*x = WriteConsumptionLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteConsumptionLimitResponse) ProtoMessage() {}

func (x *WriteConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*WriteConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{3}
}

func (x *WriteConsumptionLimitResponse) GetErrorNumber() uint64 {
	if x != nil && x.ErrorNumber != nil {
		return *x.ErrorNumber
	}
	return 0
}

func (x *WriteConsumptionLimitResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *WriteConsumptionLimitResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type FailsafeConsumptionActivePowerLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
}

func (x *FailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = FailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{4}
}

func (x *FailsafeConsumptionActivePowerLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *FailsafeConsumptionActivePowerLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type FailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit float64 `protobuf:"fixed64,1,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *FailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = FailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{5}
}

func (x *FailsafeConsumptionActivePowerLimitResponse) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WriteFailsafeConsumptionActivePowerLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	Limit               float64                     `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = WriteFailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*WriteFailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{6}
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteFailsafeConsumptionActivePowerLimitRequest) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type WriteFailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgCounter uint64 `protobuf:"varint,1,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = WriteFailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*WriteFailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFailsafeConsumptionActivePowerLimitResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type FailsafeDurationMinimumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
}

func (x *FailsafeDurationMinimumRequest) Reset() {
	*x = FailsafeDurationMinimumRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *FailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{8}
}

func (x *FailsafeDurationMinimumRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *FailsafeDurationMinimumRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type FailsafeDurationMinimumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DurationNanoseconds uint64 `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
}

func (x *FailsafeDurationMinimumResponse) Reset() {
	*x = FailsafeDurationMinimumResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *FailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FailsafeDurationMinimumResponse) GetDurationNanoseconds() uint64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

type WriteFailsafeDurationMinimumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
	DurationNanoseconds uint64                      `protobuf:"varint,3,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
}

func (x *WriteFailsafeDurationMinimumRequest) Reset() {
	*x = WriteFailsafeDurationMinimumRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *WriteFailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*WriteFailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{10}
}

func (x *WriteFailsafeDurationMinimumRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *WriteFailsafeDurationMinimumRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

func (x *WriteFailsafeDurationMinimumRequest) GetDurationNanoseconds() uint64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

type WriteFailsafeDurationMinimumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgCounter uint64 `protobuf:"varint,1,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
}

func (x *WriteFailsafeDurationMinimumResponse) Reset() {
	*x = WriteFailsafeDurationMinimumResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *WriteFailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*WriteFailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{11}
}

func (x *WriteFailsafeDurationMinimumResponse) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

type StartHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartHeartbeatRequest) Reset() {
	*x = StartHeartbeatRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatRequest) ProtoMessage() {}

func (x *StartHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StartHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{12}
}

type StartHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartHeartbeatResponse) Reset() {
	*x = StartHeartbeatResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatResponse) ProtoMessage() {}

func (x *StartHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StartHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{13}
}

type StopHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopHeartbeatRequest) Reset() {
	*x = StopHeartbeatRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatRequest) ProtoMessage() {}

func (x *StopHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StopHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{14}
}

type StopHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopHeartbeatResponse) Reset() {
	*x = StopHeartbeatResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatResponse) ProtoMessage() {}

func (x *StopHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StopHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{15}
}

type IsHeartbeatWithinDurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
}

func (x *IsHeartbeatWithinDurationRequest) Reset() {
	*x = IsHeartbeatWithinDurationRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationRequest) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationRequest.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{16}
}

func (x *IsHeartbeatWithinDurationRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *IsHeartbeatWithinDurationRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type IsHeartbeatWithinDurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithinDuration bool `protobuf:"varint,1,opt,name=within_duration,json=withinDuration,proto3" json:"within_duration,omitempty"`
}

func (x *IsHeartbeatWithinDurationResponse) Reset() {
	*x = IsHeartbeatWithinDurationResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationResponse) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationResponse.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{17}
}

func (x *IsHeartbeatWithinDurationResponse) GetWithinDuration() bool {
	if x != nil {
		return x.WithinDuration
	}
	return false
}

type ConsumptionNominalMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemoteSki           string                      `protobuf:"bytes,1,opt,name=remote_ski,json=remoteSki,proto3" json:"remote_ski,omitempty"`
	RemoteEntityAddress *common_types.EntityAddress `protobuf:"bytes,2,opt,name=remote_entity_address,json=remoteEntityAddress,proto3" json:"remote_entity_address,omitempty"`
}

func (x *ConsumptionNominalMaxRequest) Reset() {
	*x = ConsumptionNominalMaxRequest{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxRequest) ProtoMessage() {}

func (x *ConsumptionNominalMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxRequest) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{18}
}

func (x *ConsumptionNominalMaxRequest) GetRemoteSki() string {
	if x != nil {
		return x.RemoteSki
	}
	return ""
}

func (x *ConsumptionNominalMaxRequest) GetRemoteEntityAddress() *common_types.EntityAddress {
	if x != nil {
		return x.RemoteEntityAddress
	}
	return nil
}

type ConsumptionNominalMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumptionNominalMax float64 `protobuf:"fixed64,1,opt,name=consumption_nominal_max,json=consumptionNominalMax,proto3" json:"consumption_nominal_max,omitempty"`
}

func (x *ConsumptionNominalMaxResponse) Reset() {
	*x = ConsumptionNominalMaxResponse{}
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxResponse) ProtoMessage() {}

func (x *ConsumptionNominalMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_eg_lpc_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxResponse) Descriptor() ([]byte, []int) {
	return file_usecases_eg_lpc_messages_proto_rawDescGZIP(), []int{19}
}

func (x *ConsumptionNominalMaxResponse) GetConsumptionNominalMax() float64 {
	if x != nil {
		return x.ConsumptionNominalMax
	}
	return 0
}

var File_usecases_eg_lpc_messages_proto protoreflect.FileDescriptor

var file_usecases_eg_lpc_messages_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x75, 0x73, 0x65, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f, 0x65, 0x67, 0x2f, 0x6c, 0x70,
	0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x65, 0x67, 0x5f, 0x6c, 0x70, 0x63, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a,
	0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x49,
	0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xbd, 0x01, 0x0a, 0x1c, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x1d, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0c, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73,
	0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x42, 0x0e, 0x0a, 0x0c,
	0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9c, 0x01, 0x0a,
	0x2a, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x43, 0x0a, 0x2b, 0x46,
	0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0xb7, 0x01, 0x0a, 0x2f, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61,
	0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73,
	0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x53, 0x0a, 0x30, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22,
	0x90, 0x01, 0x0a, 0x1e, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6b,
	0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x13, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x54, 0x0a, 0x1f, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x44, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x14, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x13, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6e,
	0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0xc8, 0x01, 0x0a, 0x23, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73, 0x6b, 0x69, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x12,
	0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x13, 0x72, 0x65, 0x6d,
	0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x31, 0x0a, 0x14, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e,
	0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x13,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f,
	0x6e, 0x64, 0x73, 0x22, 0x47, 0x0a, 0x24, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c,
	0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69,
	0x6d, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d,
	0x73, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x70, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x92, 0x01, 0x0a, 0x20, 0x49, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x57, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f,
	0x73, 0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4c, 0x0a, 0x21, 0x49, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x57, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x77, 0x69,
	0x74, 0x68, 0x69, 0x6e, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x8e, 0x01, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x73,
	0x6b, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65,
	0x53, 0x6b, 0x69, 0x12, 0x4f, 0x0a, 0x15, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x13, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x57, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x15, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x2f, 0x65, 0x65, 0x62, 0x75, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65,
	0x63, 0x61, 0x73, 0x65, 0x73, 0x2f, 0x65, 0x67, 0x2f, 0x6c, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usecases_eg_lpc_messages_proto_rawDescOnce sync.Once
	file_usecases_eg_lpc_messages_proto_rawDescData = file_usecases_eg_lpc_messages_proto_rawDesc
)

func file_usecases_eg_lpc_messages_proto_rawDescGZIP() []byte {
	file_usecases_eg_lpc_messages_proto_rawDescOnce.Do(func() {
		file_usecases_eg_lpc_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_usecases_eg_lpc_messages_proto_rawDescData)
	})
	return file_usecases_eg_lpc_messages_proto_rawDescData
}

var file_usecases_eg_lpc_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_usecases_eg_lpc_messages_proto_goTypes = []any{
	(*ConsumptionLimitRequest)(nil),                          // 0: eg_lpc.ConsumptionLimitRequest
	(*ConsumptionLimitResponse)(nil),                         // 1: eg_lpc.ConsumptionLimitResponse
	(*WriteConsumptionLimitRequest)(nil),                     // 2: eg_lpc.WriteConsumptionLimitRequest
	(*WriteConsumptionLimitResponse)(nil),                    // 3: eg_lpc.WriteConsumptionLimitResponse
	(*FailsafeConsumptionActivePowerLimitRequest)(nil),       // 4: eg_lpc.FailsafeConsumptionActivePowerLimitRequest
	(*FailsafeConsumptionActivePowerLimitResponse)(nil),      // 5: eg_lpc.FailsafeConsumptionActivePowerLimitResponse
	(*WriteFailsafeConsumptionActivePowerLimitRequest)(nil),  // 6: eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest
	(*WriteFailsafeConsumptionActivePowerLimitResponse)(nil), // 7: eg_lpc.WriteFailsafeConsumptionActivePowerLimitResponse
	(*FailsafeDurationMinimumRequest)(nil),                   // 8: eg_lpc.FailsafeDurationMinimumRequest
	(*FailsafeDurationMinimumResponse)(nil),                  // 9: eg_lpc.FailsafeDurationMinimumResponse
	(*WriteFailsafeDurationMinimumRequest)(nil),              // 10: eg_lpc.WriteFailsafeDurationMinimumRequest
	(*WriteFailsafeDurationMinimumResponse)(nil),             // 11: eg_lpc.WriteFailsafeDurationMinimumResponse
	(*StartHeartbeatRequest)(nil),                            // 12: eg_lpc.StartHeartbeatRequest
	(*StartHeartbeatResponse)(nil),                           // 13: eg_lpc.StartHeartbeatResponse
	(*StopHeartbeatRequest)(nil),                             // 14: eg_lpc.StopHeartbeatRequest
	(*StopHeartbeatResponse)(nil),                            // 15: eg_lpc.StopHeartbeatResponse
	(*IsHeartbeatWithinDurationRequest)(nil),                 // 16: eg_lpc.IsHeartbeatWithinDurationRequest
	(*IsHeartbeatWithinDurationResponse)(nil),                // 17: eg_lpc.IsHeartbeatWithinDurationResponse
	(*ConsumptionNominalMaxRequest)(nil),                     // 18: eg_lpc.ConsumptionNominalMaxRequest
	(*ConsumptionNominalMaxResponse)(nil),                    // 19: eg_lpc.ConsumptionNominalMaxResponse
	(*common_types.EntityAddress)(nil),                       // 20: common_types.EntityAddress
	(*common_types.LoadLimit)(nil),                           // 21: common_types.LoadLimit
}
var file_usecases_eg_lpc_messages_proto_depIdxs = []int32{
	20, // 0: eg_lpc.ConsumptionLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	21, // 1: eg_lpc.ConsumptionLimitResponse.limit:type_name -> common_types.LoadLimit
	20, // 2: eg_lpc.WriteConsumptionLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	21, // 3: eg_lpc.WriteConsumptionLimitRequest.limit:type_name -> common_types.LoadLimit
	20, // 4: eg_lpc.FailsafeConsumptionActivePowerLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 5: eg_lpc.WriteFailsafeConsumptionActivePowerLimitRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 6: eg_lpc.FailsafeDurationMinimumRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 7: eg_lpc.WriteFailsafeDurationMinimumRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 8: eg_lpc.IsHeartbeatWithinDurationRequest.remote_entity_address:type_name -> common_types.EntityAddress
	20, // 9: eg_lpc.ConsumptionNominalMaxRequest.remote_entity_address:type_name -> common_types.EntityAddress
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_usecases_eg_lpc_messages_proto_init() }
func file_usecases_eg_lpc_messages_proto_init() {
	if File_usecases_eg_lpc_messages_proto != nil {
		return
	}
	file_usecases_eg_lpc_messages_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usecases_eg_lpc_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usecases_eg_lpc_messages_proto_goTypes,
		DependencyIndexes: file_usecases_eg_lpc_messages_proto_depIdxs,
		MessageInfos:      file_usecases_eg_lpc_messages_proto_msgTypes,
	}.Build()
	File_usecases_eg_lpc_messages_proto = out.File
	file_usecases_eg_lpc_messages_proto_rawDesc = nil
	file_usecases_eg_lpc_messages_proto_goTypes = nil
	file_usecases_eg_lpc_messages_proto_depIdxs = nil
}
