// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: usecases/cs/lpc/messages.proto

package lpc

import (
	common_types "github.com/enbility/eebus-grpc/rpc_services/common_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConsumptionLimitRequest) Reset() {
	*x = ConsumptionLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitRequest) ProtoMessage() {}

func (x *ConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{0}
}

type ConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadLimit *common_types.LoadLimit `protobuf:"bytes,1,opt,name=load_limit,json=loadLimit,proto3" json:"load_limit,omitempty"`
}

func (x *ConsumptionLimitResponse) Reset() {
	*x = ConsumptionLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionLimitResponse) ProtoMessage() {}

func (x *ConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumptionLimitResponse) GetLoadLimit() *common_types.LoadLimit {
	if x != nil {
		return x.LoadLimit
	}
	return nil
}

type SetConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadLimit *common_types.LoadLimit `protobuf:"bytes,1,opt,name=load_limit,json=loadLimit,proto3" json:"load_limit,omitempty"`
}

func (x *SetConsumptionLimitRequest) Reset() {
	*x = SetConsumptionLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionLimitRequest) ProtoMessage() {}

func (x *SetConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*SetConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SetConsumptionLimitRequest) GetLoadLimit() *common_types.LoadLimit {
	if x != nil {
		return x.LoadLimit
	}
	return nil
}

type SetConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetConsumptionLimitResponse) Reset() {
	*x = SetConsumptionLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionLimitResponse) ProtoMessage() {}

func (x *SetConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*SetConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{3}
}

type PendingConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PendingConsumptionLimitRequest) Reset() {
	*x = PendingConsumptionLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingConsumptionLimitRequest) ProtoMessage() {}

func (x *PendingConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*PendingConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{4}
}

type PendingConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoadLimits map[uint64]*common_types.LoadLimit `protobuf:"bytes,1,rep,name=load_limits,json=loadLimits,proto3" json:"load_limits,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PendingConsumptionLimitResponse) Reset() {
	*x = PendingConsumptionLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingConsumptionLimitResponse) ProtoMessage() {}

func (x *PendingConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*PendingConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{5}
}

func (x *PendingConsumptionLimitResponse) GetLoadLimits() map[uint64]*common_types.LoadLimit {
	if x != nil {
		return x.LoadLimits
	}
	return nil
}

type ApproveOrDenyConsumptionLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgCounter uint64 `protobuf:"varint,1,opt,name=msg_counter,json=msgCounter,proto3" json:"msg_counter,omitempty"`
	Approve    bool   `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	Reason     string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ApproveOrDenyConsumptionLimitRequest) Reset() {
	*x = ApproveOrDenyConsumptionLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveOrDenyConsumptionLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveOrDenyConsumptionLimitRequest) ProtoMessage() {}

func (x *ApproveOrDenyConsumptionLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveOrDenyConsumptionLimitRequest.ProtoReflect.Descriptor instead.
func (*ApproveOrDenyConsumptionLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ApproveOrDenyConsumptionLimitRequest) GetMsgCounter() uint64 {
	if x != nil {
		return x.MsgCounter
	}
	return 0
}

func (x *ApproveOrDenyConsumptionLimitRequest) GetApprove() bool {
	if x != nil {
		return x.Approve
	}
	return false
}

func (x *ApproveOrDenyConsumptionLimitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ApproveOrDenyConsumptionLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApproveOrDenyConsumptionLimitResponse) Reset() {
	*x = ApproveOrDenyConsumptionLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveOrDenyConsumptionLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveOrDenyConsumptionLimitResponse) ProtoMessage() {}

func (x *ApproveOrDenyConsumptionLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveOrDenyConsumptionLimitResponse.ProtoReflect.Descriptor instead.
func (*ApproveOrDenyConsumptionLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{7}
}

type FailsafeConsumptionActivePowerLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = FailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{8}
}

type FailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit        float64 `protobuf:"fixed64,1,opt,name=limit,proto3" json:"limit,omitempty"`
	IsChangeable bool    `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
}

func (x *FailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = FailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *FailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*FailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{9}
}

func (x *FailsafeConsumptionActivePowerLimitResponse) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FailsafeConsumptionActivePowerLimitResponse) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

type SetFailsafeConsumptionActivePowerLimitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value        float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	IsChangeable bool    `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
}

func (x *SetFailsafeConsumptionActivePowerLimitRequest) Reset() {
	*x = SetFailsafeConsumptionActivePowerLimitRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailsafeConsumptionActivePowerLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailsafeConsumptionActivePowerLimitRequest) ProtoMessage() {}

func (x *SetFailsafeConsumptionActivePowerLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailsafeConsumptionActivePowerLimitRequest.ProtoReflect.Descriptor instead.
func (*SetFailsafeConsumptionActivePowerLimitRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{10}
}

func (x *SetFailsafeConsumptionActivePowerLimitRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SetFailsafeConsumptionActivePowerLimitRequest) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

type SetFailsafeConsumptionActivePowerLimitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFailsafeConsumptionActivePowerLimitResponse) Reset() {
	*x = SetFailsafeConsumptionActivePowerLimitResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailsafeConsumptionActivePowerLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailsafeConsumptionActivePowerLimitResponse) ProtoMessage() {}

func (x *SetFailsafeConsumptionActivePowerLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailsafeConsumptionActivePowerLimitResponse.ProtoReflect.Descriptor instead.
func (*SetFailsafeConsumptionActivePowerLimitResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{11}
}

type FailsafeDurationMinimumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FailsafeDurationMinimumRequest) Reset() {
	*x = FailsafeDurationMinimumRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *FailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{12}
}

type FailsafeDurationMinimumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DurationNanoseconds int64 `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	IsChangeable        bool  `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
}

func (x *FailsafeDurationMinimumResponse) Reset() {
	*x = FailsafeDurationMinimumResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *FailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*FailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{13}
}

func (x *FailsafeDurationMinimumResponse) GetDurationNanoseconds() int64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

func (x *FailsafeDurationMinimumResponse) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

type SetFailsafeDurationMinimumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DurationNanoseconds int64 `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	IsChangeable        bool  `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
}

func (x *SetFailsafeDurationMinimumRequest) Reset() {
	*x = SetFailsafeDurationMinimumRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailsafeDurationMinimumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailsafeDurationMinimumRequest) ProtoMessage() {}

func (x *SetFailsafeDurationMinimumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailsafeDurationMinimumRequest.ProtoReflect.Descriptor instead.
func (*SetFailsafeDurationMinimumRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SetFailsafeDurationMinimumRequest) GetDurationNanoseconds() int64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

func (x *SetFailsafeDurationMinimumRequest) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

type SetFailsafeDurationMinimumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetFailsafeDurationMinimumResponse) Reset() {
	*x = SetFailsafeDurationMinimumResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailsafeDurationMinimumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailsafeDurationMinimumResponse) ProtoMessage() {}

func (x *SetFailsafeDurationMinimumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailsafeDurationMinimumResponse.ProtoReflect.Descriptor instead.
func (*SetFailsafeDurationMinimumResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{15}
}

type StartHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartHeartbeatRequest) Reset() {
	*x = StartHeartbeatRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatRequest) ProtoMessage() {}

func (x *StartHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StartHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{16}
}

type StartHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartHeartbeatResponse) Reset() {
	*x = StartHeartbeatResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartHeartbeatResponse) ProtoMessage() {}

func (x *StartHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StartHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{17}
}

type StopHeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopHeartbeatRequest) Reset() {
	*x = StopHeartbeatRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatRequest) ProtoMessage() {}

func (x *StopHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*StopHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{18}
}

type StopHeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopHeartbeatResponse) Reset() {
	*x = StopHeartbeatResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopHeartbeatResponse) ProtoMessage() {}

func (x *StopHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*StopHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{19}
}

type IsHeartbeatWithinDurationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IsHeartbeatWithinDurationRequest) Reset() {
	*x = IsHeartbeatWithinDurationRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationRequest) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationRequest.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{20}
}

type IsHeartbeatWithinDurationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsWithinDuration bool `protobuf:"varint,1,opt,name=is_within_duration,json=isWithinDuration,proto3" json:"is_within_duration,omitempty"`
}

func (x *IsHeartbeatWithinDurationResponse) Reset() {
	*x = IsHeartbeatWithinDurationResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsHeartbeatWithinDurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsHeartbeatWithinDurationResponse) ProtoMessage() {}

func (x *IsHeartbeatWithinDurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsHeartbeatWithinDurationResponse.ProtoReflect.Descriptor instead.
func (*IsHeartbeatWithinDurationResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{21}
}

func (x *IsHeartbeatWithinDurationResponse) GetIsWithinDuration() bool {
	if x != nil {
		return x.IsWithinDuration
	}
	return false
}

type ConsumptionNominalMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConsumptionNominalMaxRequest) Reset() {
	*x = ConsumptionNominalMaxRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxRequest) ProtoMessage() {}

func (x *ConsumptionNominalMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxRequest.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{22}
}

type ConsumptionNominalMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ConsumptionNominalMaxResponse) Reset() {
	*x = ConsumptionNominalMaxResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumptionNominalMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumptionNominalMaxResponse) ProtoMessage() {}

func (x *ConsumptionNominalMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumptionNominalMaxResponse.ProtoReflect.Descriptor instead.
func (*ConsumptionNominalMaxResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{23}
}

func (x *ConsumptionNominalMaxResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetConsumptionNominalMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetConsumptionNominalMaxRequest) Reset() {
	*x = SetConsumptionNominalMaxRequest{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionNominalMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionNominalMaxRequest) ProtoMessage() {}

func (x *SetConsumptionNominalMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionNominalMaxRequest.ProtoReflect.Descriptor instead.
func (*SetConsumptionNominalMaxRequest) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{24}
}

func (x *SetConsumptionNominalMaxRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetConsumptionNominalMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetConsumptionNominalMaxResponse) Reset() {
	*x = SetConsumptionNominalMaxResponse{}
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConsumptionNominalMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConsumptionNominalMaxResponse) ProtoMessage() {}

func (x *SetConsumptionNominalMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_usecases_cs_lpc_messages_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConsumptionNominalMaxResponse.ProtoReflect.Descriptor instead.
func (*SetConsumptionNominalMaxResponse) Descriptor() ([]byte, []int) {
	return file_usecases_cs_lpc_messages_proto_rawDescGZIP(), []int{25}
}

var File_usecases_cs_lpc_messages_proto protoreflect.FileDescriptor

var file_usecases_cs_lpc_messages_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x75, 0x73, 0x65, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f, 0x63, 0x73, 0x2f, 0x6c, 0x70,
	0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x63, 0x73, 0x5f, 0x6c, 0x70, 0x63, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a,
	0x18, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61,
	0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x09, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x54, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x36, 0x0a, 0x0a, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x09, 0x6c, 0x6f,
	0x61, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x1f, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x0b,
	0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x37, 0x2e, 0x63, 0x73, 0x5f, 0x6c, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x6c, 0x6f, 0x61, 0x64,
	0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x1a, 0x56, 0x0a, 0x0f, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x79,
	0x0a, 0x24, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x4f, 0x72, 0x44, 0x65, 0x6e, 0x79, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x73, 0x67, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x73, 0x67,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x27, 0x0a, 0x25, 0x41, 0x70, 0x70,
	0x72, 0x6f, 0x76, 0x65, 0x4f, 0x72, 0x44, 0x65, 0x6e, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2c, 0x0a, 0x2a, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50,
	0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x68, 0x0a, 0x2b, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77,
	0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x6a, 0x0a, 0x2d, 0x53, 0x65,
	0x74, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x2e, 0x53, 0x65, 0x74, 0x46, 0x61, 0x69,
	0x6c, 0x73, 0x61, 0x66, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x46, 0x61, 0x69, 0x6c,
	0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69,
	0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x79, 0x0a, 0x1f, 0x46, 0x61,
	0x69, 0x6c, 0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69,
	0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x14, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x7b, 0x0a, 0x21, 0x53, 0x65, 0x74, 0x46, 0x61, 0x69, 0x6c,
	0x73, 0x61, 0x66, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69,
	0x6d, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x64, 0x75,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x69, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x69, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62,
	0x6c, 0x65, 0x22, 0x24, 0x0a, 0x22, 0x53, 0x65, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x73, 0x61, 0x66,
	0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x53,
	0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x74, 0x6f, 0x70, 0x48, 0x65, 0x61, 0x72, 0x74,
	0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x20,
	0x49, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x57, 0x69, 0x74, 0x68, 0x69,
	0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x51, 0x0a, 0x21, 0x49, 0x73, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x57,
	0x69, 0x74, 0x68, 0x69, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x69, 0x73, 0x5f, 0x77, 0x69, 0x74, 0x68,
	0x69, 0x6e, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x69, 0x73, 0x57, 0x69, 0x74, 0x68, 0x69, 0x6e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x1e, 0x0a, 0x1c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x1d, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x37, 0x0a, 0x1f, 0x53, 0x65,
	0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x53, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x4d, 0x61, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x65,
	0x65, 0x62, 0x75, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f,
	0x63, 0x73, 0x2f, 0x6c, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_usecases_cs_lpc_messages_proto_rawDescOnce sync.Once
	file_usecases_cs_lpc_messages_proto_rawDescData = file_usecases_cs_lpc_messages_proto_rawDesc
)

func file_usecases_cs_lpc_messages_proto_rawDescGZIP() []byte {
	file_usecases_cs_lpc_messages_proto_rawDescOnce.Do(func() {
		file_usecases_cs_lpc_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_usecases_cs_lpc_messages_proto_rawDescData)
	})
	return file_usecases_cs_lpc_messages_proto_rawDescData
}

var file_usecases_cs_lpc_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_usecases_cs_lpc_messages_proto_goTypes = []any{
	(*ConsumptionLimitRequest)(nil),                        // 0: cs_lpc.ConsumptionLimitRequest
	(*ConsumptionLimitResponse)(nil),                       // 1: cs_lpc.ConsumptionLimitResponse
	(*SetConsumptionLimitRequest)(nil),                     // 2: cs_lpc.SetConsumptionLimitRequest
	(*SetConsumptionLimitResponse)(nil),                    // 3: cs_lpc.SetConsumptionLimitResponse
	(*PendingConsumptionLimitRequest)(nil),                 // 4: cs_lpc.PendingConsumptionLimitRequest
	(*PendingConsumptionLimitResponse)(nil),                // 5: cs_lpc.PendingConsumptionLimitResponse
	(*ApproveOrDenyConsumptionLimitRequest)(nil),           // 6: cs_lpc.ApproveOrDenyConsumptionLimitRequest
	(*ApproveOrDenyConsumptionLimitResponse)(nil),          // 7: cs_lpc.ApproveOrDenyConsumptionLimitResponse
	(*FailsafeConsumptionActivePowerLimitRequest)(nil),     // 8: cs_lpc.FailsafeConsumptionActivePowerLimitRequest
	(*FailsafeConsumptionActivePowerLimitResponse)(nil),    // 9: cs_lpc.FailsafeConsumptionActivePowerLimitResponse
	(*SetFailsafeConsumptionActivePowerLimitRequest)(nil),  // 10: cs_lpc.SetFailsafeConsumptionActivePowerLimitRequest
	(*SetFailsafeConsumptionActivePowerLimitResponse)(nil), // 11: cs_lpc.SetFailsafeConsumptionActivePowerLimitResponse
	(*FailsafeDurationMinimumRequest)(nil),                 // 12: cs_lpc.FailsafeDurationMinimumRequest
	(*FailsafeDurationMinimumResponse)(nil),                // 13: cs_lpc.FailsafeDurationMinimumResponse
	(*SetFailsafeDurationMinimumRequest)(nil),              // 14: cs_lpc.SetFailsafeDurationMinimumRequest
	(*SetFailsafeDurationMinimumResponse)(nil),             // 15: cs_lpc.SetFailsafeDurationMinimumResponse
	(*StartHeartbeatRequest)(nil),                          // 16: cs_lpc.StartHeartbeatRequest
	(*StartHeartbeatResponse)(nil),                         // 17: cs_lpc.StartHeartbeatResponse
	(*StopHeartbeatRequest)(nil),                           // 18: cs_lpc.StopHeartbeatRequest
	(*StopHeartbeatResponse)(nil),                          // 19: cs_lpc.StopHeartbeatResponse
	(*IsHeartbeatWithinDurationRequest)(nil),               // 20: cs_lpc.IsHeartbeatWithinDurationRequest
	(*IsHeartbeatWithinDurationResponse)(nil),              // 21: cs_lpc.IsHeartbeatWithinDurationResponse
	(*ConsumptionNominalMaxRequest)(nil),                   // 22: cs_lpc.ConsumptionNominalMaxRequest
	(*ConsumptionNominalMaxResponse)(nil),                  // 23: cs_lpc.ConsumptionNominalMaxResponse
	(*SetConsumptionNominalMaxRequest)(nil),                // 24: cs_lpc.SetConsumptionNominalMaxRequest
	(*SetConsumptionNominalMaxResponse)(nil),               // 25: cs_lpc.SetConsumptionNominalMaxResponse
	nil,                                                    // 26: cs_lpc.PendingConsumptionLimitResponse.LoadLimitsEntry
	(*common_types.LoadLimit)(nil),                         // 27: common_types.LoadLimit
}
var file_usecases_cs_lpc_messages_proto_depIdxs = []int32{
	27, // 0: cs_lpc.ConsumptionLimitResponse.load_limit:type_name -> common_types.LoadLimit
	27, // 1: cs_lpc.SetConsumptionLimitRequest.load_limit:type_name -> common_types.LoadLimit
	26, // 2: cs_lpc.PendingConsumptionLimitResponse.load_limits:type_name -> cs_lpc.PendingConsumptionLimitResponse.LoadLimitsEntry
	27, // 3: cs_lpc.PendingConsumptionLimitResponse.LoadLimitsEntry.value:type_name -> common_types.LoadLimit
	4,  // [4:4] is the sub-list for method output_type
	4,  // [4:4] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_usecases_cs_lpc_messages_proto_init() }
func file_usecases_cs_lpc_messages_proto_init() {
	if File_usecases_cs_lpc_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_usecases_cs_lpc_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usecases_cs_lpc_messages_proto_goTypes,
		DependencyIndexes: file_usecases_cs_lpc_messages_proto_depIdxs,
		MessageInfos:      file_usecases_cs_lpc_messages_proto_msgTypes,
	}.Build()
	File_usecases_cs_lpc_messages_proto = out.File
	file_usecases_cs_lpc_messages_proto_rawDesc = nil
	file_usecases_cs_lpc_messages_proto_goTypes = nil
	file_usecases_cs_lpc_messages_proto_depIdxs = nil
}
