// SPDX-License-Identifier: Apache-2.0
// Copyright Pionix GmbH and Contributors to EVerest

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.12
// source: common_types/types.proto

package common_types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadLimit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DurationNanoseconds int64   `protobuf:"varint,1,opt,name=duration_nanoseconds,json=durationNanoseconds,proto3" json:"duration_nanoseconds,omitempty"`
	IsChangeable        bool    `protobuf:"varint,2,opt,name=is_changeable,json=isChangeable,proto3" json:"is_changeable,omitempty"`
	IsActive            bool    `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Value               float64 `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	DeleteDuration      bool    `protobuf:"varint,5,opt,name=delete_duration,json=deleteDuration,proto3" json:"delete_duration,omitempty"`
}

func (x *LoadLimit) Reset() {
	*x = LoadLimit{}
	mi := &file_common_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadLimit) ProtoMessage() {}

func (x *LoadLimit) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadLimit.ProtoReflect.Descriptor instead.
func (*LoadLimit) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *LoadLimit) GetDurationNanoseconds() int64 {
	if x != nil {
		return x.DurationNanoseconds
	}
	return 0
}

func (x *LoadLimit) GetIsChangeable() bool {
	if x != nil {
		return x.IsChangeable
	}
	return false
}

func (x *LoadLimit) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *LoadLimit) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *LoadLimit) GetDeleteDuration() bool {
	if x != nil {
		return x.DeleteDuration
	}
	return false
}

type EntityAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityAddress []uint32 `protobuf:"varint,1,rep,packed,name=entity_address,json=entityAddress,proto3" json:"entity_address,omitempty"`
}

func (x *EntityAddress) Reset() {
	*x = EntityAddress{}
	mi := &file_common_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityAddress) ProtoMessage() {}

func (x *EntityAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityAddress.ProtoReflect.Descriptor instead.
func (*EntityAddress) Descriptor() ([]byte, []int) {
	return file_common_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *EntityAddress) GetEntityAddress() []uint32 {
	if x != nil {
		return x.EntityAddress
	}
	return nil
}

var File_common_types_types_proto protoreflect.FileDescriptor

var file_common_types_types_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x4c, 0x6f, 0x61,
	0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x13, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61,
	0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x73, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0c, 0x69, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0d, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x0d, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x65, 0x6e, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2f, 0x65, 0x65, 0x62, 0x75, 0x73, 0x2d,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_types_types_proto_rawDescOnce sync.Once
	file_common_types_types_proto_rawDescData = file_common_types_types_proto_rawDesc
)

func file_common_types_types_proto_rawDescGZIP() []byte {
	file_common_types_types_proto_rawDescOnce.Do(func() {
		file_common_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_types_types_proto_rawDescData)
	})
	return file_common_types_types_proto_rawDescData
}

var file_common_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_types_types_proto_goTypes = []any{
	(*LoadLimit)(nil),     // 0: common_types.LoadLimit
	(*EntityAddress)(nil), // 1: common_types.EntityAddress
}
var file_common_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_types_types_proto_init() }
func file_common_types_types_proto_init() {
	if File_common_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_types_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_types_proto_goTypes,
		DependencyIndexes: file_common_types_types_proto_depIdxs,
		MessageInfos:      file_common_types_types_proto_msgTypes,
	}.Build()
	File_common_types_types_proto = out.File
	file_common_types_types_proto_rawDesc = nil
	file_common_types_types_proto_goTypes = nil
	file_common_types_types_proto_depIdxs = nil
}
